-- ==============================================================================
-- SKRIP SQL PEMBUATAN TABEL PETERNAKAN KOTA CILEGON (SUPABASE)
-- ==============================================================================

-- 1. Buat Tabel Peternakan
CREATE TABLE IF NOT EXISTS public.peternakan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    pemilik TEXT NOT NULL,
    kecamatan TEXT NOT NULL,
    kelurahan TEXT DEFAULT '-',
    sapi INT DEFAULT 0,
    kambing INT DEFAULT 0,
    ayam INT DEFAULT 0,
    itik INT DEFAULT 0,
    lat NUMERIC DEFAULT 0,
    lng NUMERIC DEFAULT 0,
    catatan TEXT DEFAULT '[]',
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

-- 2. Aktifkan Row Level Security (RLS)
ALTER TABLE public.peternakan ENABLE ROW LEVEL SECURITY;

-- 3. Kebijakan Hak Akses (RLS Policies):
-- A. Semua orang (Public / Guest) dapat melihat data (Read-Only)
CREATE POLICY "Public Read Peternakan" 
ON public.peternakan 
FOR SELECT 
USING (true);

-- B. Pengguna terautentikasi dapat menambah data
CREATE POLICY "Authenticated Insert Peternakan" 
ON public.peternakan 
FOR INSERT 
TO authenticated 
WITH CHECK (true);

-- C. Super Admin (ketapangcilegon@gmail.com) atau pemilik data dapat mengedit
CREATE POLICY "Super Admin and Owner Update Peternakan" 
ON public.peternakan 
FOR UPDATE 
TO authenticated 
USING (
    (auth.jwt() ->> 'email' = 'ketapangcilegon@gmail.com') OR (auth.uid() = user_id)
);

-- D. Super Admin (ketapangcilegon@gmail.com) atau pemilik data dapat menghapus
CREATE POLICY "Super Admin and Owner Delete Peternakan" 
ON public.peternakan 
FOR DELETE 
TO authenticated 
USING (
    (auth.jwt() ->> 'email' = 'ketapangcilegon@gmail.com') OR (auth.uid() = user_id)
);

-- 4. Data Awal (Seed Data) Kota Cilegon Sesuai Mockup
INSERT INTO public.peternakan (pemilik, kecamatan, kelurahan, sapi, kambing, ayam, itik, lat, lng) VALUES
('Kelompok Ternak Berkah Jaya', 'Cibeber', 'Kedaleman', 12, 25, 150, 0, -6.0331, 106.0696),
('Peternakan Unggas Mandiri', 'Jombang', 'Masigit', 0, 8, 400, 0, -6.0125, 106.0543),
('Kandang Sapi Barokah', 'Citangkil', 'Warnasari', 18, 15, 0, 0, -6.0198, 106.0287)
ON CONFLICT DO NOTHING;
